[package]
name = "nethon_token_transfer"
type = "bin"
authors = ["wdc1209"] 
compiler_version = ">=0.20.0" # Adjust if necessary, e.g., "0.27.0"

[dependencies]
# For pedersen_hash; adjust tag/version as per your Noir setup and latest noir-libs release.
noir_stdlib = { tag = "v0.6.0", git = "https://github.com/noir-lang/noir-libs/" , directory="stdlib"}